In [22]:
import numpy as np
import pandas as pd
import random
from keras.preprocessing import image
from sklearn import svm
from matplotlib import pyplot as plt

In [23]:
df = pd.read_csv("./Train/train.csv")
train_csv = df.values

train_csv.shape

(304, 2)

In [153]:
img_base_path = "./Train/Images/"

labels = {"Pikachu":0, "Bulbasaur":1, "Charmander":2}

image_data = []
image_labels = []


for train_item in train_csv:
    #print(img_path)
    img = image.load_img(img_base_path+train_item[0], target_size=(32,32))
    img_array = image.img_to_array(img)
    
    image_data.append(img_array)
    image_labels.append(labels[train_item[1]])

/usr/lib/python3/dist-packages/PIL/Image.py:993: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


In [154]:
print(len(image_data), len(image_labels))
print(image_labels[0], image_data[0])

304 304
0 [[[146. 191. 232.]
  [148. 191. 233.]
  [149. 193. 232.]
  ...
  [154. 196. 234.]
  [152. 196. 233.]
  [150. 193. 235.]]

 [[149. 193. 232.]
  [152. 196. 235.]
  [152. 196. 233.]
  ...
  [159. 199. 235.]
  [154. 197. 232.]
  [152. 196. 233.]]

 [[149. 192. 234.]
  [150. 194. 233.]
  [152. 196. 233.]
  ...
  [160. 200. 235.]
  [156. 199. 234.]
  [152. 196. 233.]]

 ...

 [[ 82. 142. 212.]
  [ 79. 139. 211.]
  [ 79. 137. 210.]
  ...
  [ 74. 133. 209.]
  [ 74. 133. 209.]
  [ 74. 133. 209.]]

 [[ 82. 140. 213.]
  [ 79. 137. 211.]
  [ 76. 136. 209.]
  ...
  [ 74. 133. 209.]
  [ 74. 133. 209.]
  [ 74. 133. 209.]]

 [[ 80. 140. 212.]
  [ 78. 138. 211.]
  [ 76. 136. 209.]
  ...
  [ 76. 136. 209.]
  [ 77. 137. 210.]
  [ 78. 136. 210.]]]


In [155]:
X = np.array(image_data, dtype="float32")/255.0
Y = np.array(image_labels)

print(X.shape, Y.shape)

(304, 32, 32, 3) (304,)


In [156]:
combined = list(zip(X, Y))
random.shuffle(combined)

X[:], Y[:] = zip(*combined)

In [157]:
m = X.shape[0]
X = X.reshape(m,-1)
print(X.shape, Y.shape)

(304, 3072) (304,)


In [158]:
svm_classifier = svm.SVC(kernel="linear", C=1.0)

svm_classifier.fit(X, Y)
svm_classifier.score(X, Y)

0.7138157894736842

In [159]:
dft = pd.read_csv("./Test/test.csv")
test_csv = dft.values

test_csv.shape

(123, 1)

In [160]:
img_base_path_t = "./Test/Images/"

image_data_t = []

for test_item in test_csv:
    img = image.load_img(img_base_path_t+test_item[0], target_size=(32,32))
    img_array = image.img_to_array(img)
    
    image_data_t.append(img_array)

In [161]:
X_ = np.array(image_data_t, dtype="float32")/255.0
X_ = X_.reshape(X_.shape[0],-1)
print(X_.shape)
X_

(123, 3072)


array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.8509804 , 0.8509804 , 0.8509804 , ..., 0.8509804 , 0.8509804 ,
        0.8509804 ],
       [0.1882353 , 0.5019608 , 0.41960785, ..., 0.6745098 , 0.8117647 ,
        0.34901962],
       [0.42745098, 0.42745098, 0.42745098, ..., 0.05882353, 0.05882353,
        0.05882353]], dtype=float32)

In [162]:
Y_ = svm_classifier.predict(X_)

In [163]:
print(Y_.shape)
print(X_[1], Y_[1])

(123,)
[1. 1. 1. ... 1. 1. 1.] 2


In [164]:
list(labels.keys())[list(labels.values()).index(0)]

'Pikachu'

In [165]:
with open("./output_pokemon.csv", "w") as f:
    for i in range(Y_.shape[0]):
        print(list(labels.keys())[list(labels.values()).index(Y_[i])], Y_[i])
        s = str(test_csv[i][0])+","+list(labels.keys())[list(labels.values()).index(Y_[i])]+"\n"
        f.write(s)

Bulbasaur 1
Charmander 2
Bulbasaur 1
Pikachu 0
Charmander 2
Pikachu 0
Charmander 2
Pikachu 0
Bulbasaur 1
Charmander 2
Bulbasaur 1
Bulbasaur 1
Bulbasaur 1
Bulbasaur 1
Bulbasaur 1
Bulbasaur 1
Charmander 2
Charmander 2
Charmander 2
Charmander 2
Pikachu 0
Bulbasaur 1
Charmander 2
Bulbasaur 1
Pikachu 0
Charmander 2
Bulbasaur 1
Bulbasaur 1
Pikachu 0
Pikachu 0
Pikachu 0
Charmander 2
Charmander 2
Pikachu 0
Pikachu 0
Bulbasaur 1
Bulbasaur 1
Bulbasaur 1
Charmander 2
Bulbasaur 1
Bulbasaur 1
Charmander 2
Charmander 2
Charmander 2
Charmander 2
Bulbasaur 1
Charmander 2
Bulbasaur 1
Charmander 2
Charmander 2
Pikachu 0
Charmander 2
Charmander 2
Bulbasaur 1
Charmander 2
Bulbasaur 1
Charmander 2
Pikachu 0
Pikachu 0
Charmander 2
Charmander 2
Pikachu 0
Charmander 2
Pikachu 0
Charmander 2
Charmander 2
Pikachu 0
Pikachu 0
Charmander 2
Pikachu 0
Pikachu 0
Bulbasaur 1
Pikachu 0
Pikachu 0
Charmander 2
Charmander 2
Charmander 2
Charmander 2
Charmander 2
Bulbasaur 1
Pikachu 0
Bulbasaur 1
Charmander 2
Bulbasaur 1
